server {
    listen 80;

    client_max_body_size 20M;

    # API (FastAPI backend)
    location /api/ {
        proxy_pass       http://library_backend:8000/api/;
        proxy_set_header Host        $host;
        proxy_set_header X-Real-IP   $remote_addr;
    }

    # Swagger docs
    location /docs {
        proxy_pass       http://library_backend:8000/docs;
        proxy_set_header Host        $host;
        proxy_set_header X-Real-IP   $remote_addr;
    }

    # ReDoc
    location /redoc {
        proxy_pass       http://library_backend:8000/redoc;
        proxy_set_header Host        $host;
        proxy_set_header X-Real-IP   $remote_addr;
    }

    # OpenAPI JSON (обязательно для Swagger UI)
    location /openapi.json {
        proxy_pass       http://library_backend:8000/openapi.json;
        proxy_set_header Host        $host;
        proxy_set_header X-Real-IP   $remote_addr;
    }

    # Статика от backend
    location /static/ {
        alias /app/static/;
    }

    # SPA фронтенд
    location / {
        root      /usr/share/nginx/html;
        index     index.html;
        try_files $uri $uri/ /index.html;
    }
}
